// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtI9rP58NdLYPv6QwIYIX8lAqYUiPcLwg',
    appId: '1:550292019140:web:8d2cb00929db7eb941f691',
    messagingSenderId: '550292019140',
    projectId: 'sanskrit-ai-d83ab',
    authDomain: 'sanskrit-ai-d83ab.firebaseapp.com',
    storageBucket: 'sanskrit-ai-d83ab.firebasestorage.app',
    measurementId: 'G-M8KB2KLX5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBYgZiXYsJrTe81b8XvCuJKMoop-mAOVQ',
    appId: '1:550292019140:android:f50296f1b55b1f8541f691',
    messagingSenderId: '550292019140',
    projectId: 'sanskrit-ai-d83ab',
    storageBucket: 'sanskrit-ai-d83ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgLPDebVznXsnwMxo-2jxpCErZk_2Gqxs',
    appId: '1:550292019140:ios:22c872202369890741f691',
    messagingSenderId: '550292019140',
    projectId: 'sanskrit-ai-d83ab',
    storageBucket: 'sanskrit-ai-d83ab.firebasestorage.app',
    iosBundleId: 'com.example.sanskritLearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgLPDebVznXsnwMxo-2jxpCErZk_2Gqxs',
    appId: '1:550292019140:ios:22c872202369890741f691',
    messagingSenderId: '550292019140',
    projectId: 'sanskrit-ai-d83ab',
    storageBucket: 'sanskrit-ai-d83ab.firebasestorage.app',
    iosBundleId: 'com.example.sanskritLearningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtI9rP58NdLYPv6QwIYIX8lAqYUiPcLwg',
    appId: '1:550292019140:web:efaecae6a769de7641f691',
    messagingSenderId: '550292019140',
    projectId: 'sanskrit-ai-d83ab',
    authDomain: 'sanskrit-ai-d83ab.firebaseapp.com',
    storageBucket: 'sanskrit-ai-d83ab.firebasestorage.app',
    measurementId: 'G-8S3HS51ZGH',
  );
}
